import { Open_Sans } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./pages/Shared/Cart/CartProvider";
import Navbar from "./pages/Navbar/Navbar";
import Footer from "./pages/Shared/Footer/Footer";

// Using Open Sans font with lighter weights for a more subtle look
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500"], // Light, regular, and medium weights
});

export const metadata = {
  title: "bytezle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" href="../../public/favicon.ico" />
      </head>
      <body className={openSans.className}>
        <CartProvider>
          <div className="fixed top-0 left-0 w-full z-50">
            <Navbar />
          </div>
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}